/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period38ConfigInfo {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::Dbv0Period0Period38Meta>>,
    /// Slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::Dbv0Period0Period38Error>>,
    /// Array of TRES
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Vec<Vec<crate::models::Dbv0038TresListInner>>>,
    /// Array of accounts
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<crate::models::Dbv0Period0Period38Account>>,
    /// Array of associations
    #[serde(rename = "associations", skip_serializing_if = "Option::is_none")]
    pub associations: Option<Vec<crate::models::Dbv0Period0Period38Association>>,
    /// Array of users
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::Dbv0Period0Period38User>>,
    /// Array of qos
    #[serde(rename = "qos", skip_serializing_if = "Option::is_none")]
    pub qos: Option<Vec<crate::models::Dbv0Period0Period38Qos>>,
    /// Array of wckeys
    #[serde(rename = "wckeys", skip_serializing_if = "Option::is_none")]
    pub wckeys: Option<Vec<crate::models::Dbv0Period0Period38Wckey>>,
}

impl Dbv0Period0Period38ConfigInfo {
    pub fn new() -> Dbv0Period0Period38ConfigInfo {
        Dbv0Period0Period38ConfigInfo {
            meta: None,
            errors: None,
            tres: None,
            accounts: None,
            associations: None,
            users: None,
            qos: None,
            wckeys: None,
        }
    }
}


