/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobStepStepHet : Heterogeneous job details



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobStepStepHet {
    /// Parent HetJob component id
    #[serde(rename = "component", skip_serializing_if = "Option::is_none")]
    pub component: Option<i32>,
}

impl Dbv0038JobStepStepHet {
    /// Heterogeneous job details
    pub fn new() -> Dbv0038JobStepStepHet {
        Dbv0038JobStepStepHet {
            component: None,
        }
    }
}


