/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037AssociationMaxJobs : Max jobs settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037AssociationMaxJobs {
    /// Max TRES for active total jobs
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<i32>,
    /// Max TRES for job accruing priority
    #[serde(rename = "accruing", skip_serializing_if = "Option::is_none")]
    pub accruing: Option<i32>,
    /// Max TRES for job total submitted
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0037AssociationMaxJobsPer>>,
}

impl Dbv0037AssociationMaxJobs {
    /// Max jobs settings
    pub fn new() -> Dbv0037AssociationMaxJobs {
        Dbv0037AssociationMaxJobs {
            active: None,
            accruing: None,
            total: None,
            per: None,
        }
    }
}


