/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037QosPreempt : Preemption settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037QosPreempt {
    /// List of preemptable QOS
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<String>>,
    /// List of preemption modes
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Vec<String>>,
    /// Grace period (s) before jobs can preempted
    #[serde(rename = "exempt_time", skip_serializing_if = "Option::is_none")]
    pub exempt_time: Option<i32>,
}

impl Dbv0037QosPreempt {
    /// Preemption settings
    pub fn new() -> Dbv0037QosPreempt {
        Dbv0037QosPreempt {
            list: None,
            mode: None,
            exempt_time: None,
        }
    }
}


