/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038AssociationMaxJobs : Max jobs settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038AssociationMaxJobs {
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0038AssociationMaxJobsPer>>,
}

impl Dbv0038AssociationMaxJobs {
    /// Max jobs settings
    pub fn new() -> Dbv0038AssociationMaxJobs {
        Dbv0038AssociationMaxJobs {
            per: None,
        }
    }
}


