/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038AssociationMin : Min settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038AssociationMin {
    /// Min priority threshold
    #[serde(rename = "priority_threshold", skip_serializing_if = "Option::is_none")]
    pub priority_threshold: Option<i32>,
}

impl Dbv0038AssociationMin {
    /// Min settings
    pub fn new() -> Dbv0038AssociationMin {
        Dbv0038AssociationMin {
            priority_threshold: None,
        }
    }
}


