/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037QosLimitsMaxTresPer : Max TRES per settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037QosLimitsMaxTresPer {
    /// TRES list of attributes
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<Vec<crate::models::Dbv0037TresListInner>>,
    /// TRES list of attributes
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<Vec<crate::models::Dbv0037TresListInner>>,
    /// TRES list of attributes
    #[serde(rename = "node", skip_serializing_if = "Option::is_none")]
    pub node: Option<Vec<crate::models::Dbv0037TresListInner>>,
    /// TRES list of attributes
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Vec<crate::models::Dbv0037TresListInner>>,
}

impl Dbv0037QosLimitsMaxTresPer {
    /// Max TRES per settings
    pub fn new() -> Dbv0037QosLimitsMaxTresPer {
        Dbv0037QosLimitsMaxTresPer {
            account: None,
            job: None,
            node: None,
            user: None,
        }
    }
}


