/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobArrayLimitsMax : Limits on array settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobArrayLimitsMax {
    #[serde(rename = "running", skip_serializing_if = "Option::is_none")]
    pub running: Option<Box<crate::models::Dbv0038JobArrayLimitsMaxRunning>>,
}

impl Dbv0038JobArrayLimitsMax {
    /// Limits on array settings
    pub fn new() -> Dbv0038JobArrayLimitsMax {
        Dbv0038JobArrayLimitsMax {
            running: None,
        }
    }
}


