/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period39Meta {
    #[serde(rename = "plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<Box<crate::models::V0039MetaPlugin>>,
    #[serde(rename = "Slurm", skip_serializing_if = "Option::is_none")]
    pub slurm: Option<Box<crate::models::V0039MetaSlurm>>,
}

impl Dbv0Period0Period39Meta {
    pub fn new() -> Dbv0Period0Period39Meta {
        Dbv0Period0Period39Meta {
            plugin: None,
            slurm: None,
        }
    }
}


