/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038AssociationMaxTresMinutes : Max TRES minutes settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038AssociationMaxTresMinutes {
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0038AssociationMaxTresMinutesPer>>,
    /// TRES list of attributes
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<Vec<crate::models::Dbv0038TresListInner>>,
}

impl Dbv0038AssociationMaxTresMinutes {
    /// Max TRES minutes settings
    pub fn new() -> Dbv0038AssociationMaxTresMinutes {
        Dbv0038AssociationMaxTresMinutes {
            per: None,
            total: None,
        }
    }
}


