/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period38Accounting {
    /// total seconds allocated
    #[serde(rename = "allocated", skip_serializing_if = "Option::is_none")]
    pub allocated: Option<i32>,
    /// association/wckey ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// UNIX timestamp when accounting period started
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    /// TRES list of attributes
    #[serde(rename = "TRES", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Vec<crate::models::Dbv0038TresListInner>>,
}

impl Dbv0Period0Period38Accounting {
    pub fn new() -> Dbv0Period0Period38Accounting {
        Dbv0Period0Period38Accounting {
            allocated: None,
            id: None,
            start: None,
            tres: None,
        }
    }
}


