/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037DiagStatisticsUsersInner : Statistics by user RPCs



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037DiagStatisticsUsersInner {
    /// User name
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// Number of RPCs
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::Dbv0037DiagStatisticsUsersInnerTime>>,
}

impl Dbv0037DiagStatisticsUsersInner {
    /// Statistics by user RPCs
    pub fn new() -> Dbv0037DiagStatisticsUsersInner {
        Dbv0037DiagStatisticsUsersInner {
            user: None,
            count: None,
            time: None,
        }
    }
}


