/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobStepStatistics : Statistics of job step



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobStepStatistics {
    #[serde(rename = "CPU", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<Box<crate::models::Dbv0037JobStepStatisticsCpu>>,
    #[serde(rename = "energy", skip_serializing_if = "Option::is_none")]
    pub energy: Option<Box<crate::models::Dbv0037JobStepStatisticsEnergy>>,
}

impl Dbv0037JobStepStatistics {
    /// Statistics of job step
    pub fn new() -> Dbv0037JobStepStatistics {
        Dbv0037JobStepStatistics {
            cpu: None,
            energy: None,
        }
    }
}


