/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobExitCodeSignal : Signal details (if signaled)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobExitCodeSignal {
    /// Signal number process received
    #[serde(rename = "signal_id", skip_serializing_if = "Option::is_none")]
    pub signal_id: Option<i32>,
    /// Name of signal received
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl Dbv0038JobExitCodeSignal {
    /// Signal details (if signaled)
    pub fn new() -> Dbv0038JobExitCodeSignal {
        Dbv0038JobExitCodeSignal {
            signal_id: None,
            name: None,
        }
    }
}


