/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobRequired : Job run requirements



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobRequired {
    /// Required number of CPUs
    #[serde(rename = "CPUs", skip_serializing_if = "Option::is_none")]
    pub cpus: Option<i32>,
    /// Required amount of memory (MiB)
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<i32>,
}

impl Dbv0038JobRequired {
    /// Job run requirements
    pub fn new() -> Dbv0038JobRequired {
        Dbv0038JobRequired {
            cpus: None,
            memory: None,
        }
    }
}


