/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038AssociationMaxJobsPer : Max jobs per settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038AssociationMaxJobsPer {
    /// Max wallclock per job
    #[serde(rename = "wall_clock", skip_serializing_if = "Option::is_none")]
    pub wall_clock: Option<i32>,
}

impl Dbv0038AssociationMaxJobsPer {
    /// Max jobs per settings
    pub fn new() -> Dbv0038AssociationMaxJobsPer {
        Dbv0038AssociationMaxJobsPer {
            wall_clock: None,
        }
    }
}


