/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobMcs : Multi-Category Security



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobMcs {
    /// Assigned MCS label
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl Dbv0037JobMcs {
    /// Multi-Category Security
    pub fn new() -> Dbv0037JobMcs {
        Dbv0037JobMcs {
            label: None,
        }
    }
}


