/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038QosLimitsMin : Min limit settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038QosLimitsMin {
    /// Min priority threshold
    #[serde(rename = "priority_threshold", skip_serializing_if = "Option::is_none")]
    pub priority_threshold: Option<i32>,
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Box<crate::models::Dbv0038QosLimitsMinTres>>,
}

impl Dbv0038QosLimitsMin {
    /// Min limit settings
    pub fn new() -> Dbv0038QosLimitsMin {
        Dbv0038QosLimitsMin {
            priority_threshold: None,
            tres: None,
        }
    }
}


