/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037QosLimitsMaxTres : Limits on TRES



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037QosLimitsMaxTres {
    #[serde(rename = "minutes", skip_serializing_if = "Option::is_none")]
    pub minutes: Option<Box<crate::models::Dbv0037QosLimitsMaxTresMinutes>>,
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0037QosLimitsMaxTresPer>>,
}

impl Dbv0037QosLimitsMaxTres {
    /// Limits on TRES
    pub fn new() -> Dbv0037QosLimitsMaxTres {
        Dbv0037QosLimitsMaxTres {
            minutes: None,
            per: None,
        }
    }
}


