/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038QosLimitsMaxAccruing : Limits on accruing priority



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038QosLimitsMaxAccruing {
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0038QosLimitsMaxAccruingPer>>,
}

impl Dbv0038QosLimitsMaxAccruing {
    /// Limits on accruing priority
    pub fn new() -> Dbv0038QosLimitsMaxAccruing {
        Dbv0038QosLimitsMaxAccruing {
            per: None,
        }
    }
}


