/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobStepCpuRequestedFrequency : CPU frequency requested



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobStepCpuRequestedFrequency {
    /// Min CPU frequency
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<i32>,
    /// Max CPU frequency
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<i32>,
}

impl Dbv0037JobStepCpuRequestedFrequency {
    /// CPU frequency requested
    pub fn new() -> Dbv0037JobStepCpuRequestedFrequency {
        Dbv0037JobStepCpuRequestedFrequency {
            min: None,
            max: None,
        }
    }
}


