/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobStepStep : Step details



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobStepStep {
    /// Parent job id
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<i32>,
    #[serde(rename = "het", skip_serializing_if = "Option::is_none")]
    pub het: Option<Box<crate::models::Dbv0038JobStepStepHet>>,
    /// Step id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Step name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl Dbv0038JobStepStep {
    /// Step details
    pub fn new() -> Dbv0038JobStepStep {
        Dbv0038JobStepStep {
            job_id: None,
            het: None,
            id: None,
            name: None,
        }
    }
}


