/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038DiagStatisticsUsersInnerTime : Time values



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038DiagStatisticsUsersInnerTime {
    /// Average time spent processing each user RPC
    #[serde(rename = "average", skip_serializing_if = "Option::is_none")]
    pub average: Option<i32>,
    /// Total time spent processing each user RPC
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl Dbv0038DiagStatisticsUsersInnerTime {
    /// Time values
    pub fn new() -> Dbv0038DiagStatisticsUsersInnerTime {
        Dbv0038DiagStatisticsUsersInnerTime {
            average: None,
            total: None,
        }
    }
}


