/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038QosLimitsMinTresPer : Min tres per settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038QosLimitsMinTresPer {
    /// TRES list of attributes
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<Vec<crate::models::Dbv0038TresListInner>>,
}

impl Dbv0038QosLimitsMinTresPer {
    /// Min tres per settings
    pub fn new() -> Dbv0038QosLimitsMinTresPer {
        Dbv0038QosLimitsMinTresPer {
            job: None,
        }
    }
}


