/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038QosLimitsMaxJobsActiveJobs : Limits on active jobs settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038QosLimitsMaxJobsActiveJobs {
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0038QosLimitsMaxJobsActiveJobsPer>>,
}

impl Dbv0038QosLimitsMaxJobsActiveJobs {
    /// Limits on active jobs settings
    pub fn new() -> Dbv0038QosLimitsMaxJobsActiveJobs {
        Dbv0038QosLimitsMaxJobsActiveJobs {
            per: None,
        }
    }
}


