/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobStepCpu : CPU properties



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobStepCpu {
    #[serde(rename = "requested_frequency", skip_serializing_if = "Option::is_none")]
    pub requested_frequency: Option<Box<crate::models::Dbv0037JobStepCpuRequestedFrequency>>,
    /// CPU governor
    #[serde(rename = "governor", skip_serializing_if = "Option::is_none")]
    pub governor: Option<Vec<String>>,
}

impl Dbv0037JobStepCpu {
    /// CPU properties
    pub fn new() -> Dbv0037JobStepCpu {
        Dbv0037JobStepCpu {
            requested_frequency: None,
            governor: None,
        }
    }
}


