/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobHet : Heterogeneous Job details (optional)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobHet {
    /// Parent HetJob id
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<serde_json::Value>,
    /// Offset of this job to parent
    #[serde(rename = "job_offset", skip_serializing_if = "Option::is_none")]
    pub job_offset: Option<serde_json::Value>,
}

impl Dbv0037JobHet {
    /// Heterogeneous Job details (optional)
    pub fn new() -> Dbv0037JobHet {
        Dbv0037JobHet {
            job_id: None,
            job_offset: None,
        }
    }
}


