/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period38CoordinatorInfo {
    /// Name of user
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// If user is coordinator of this account directly or coordinator status was inheirted from a higher account in the tree
    #[serde(rename = "direct", skip_serializing_if = "Option::is_none")]
    pub direct: Option<i32>,
}

impl Dbv0Period0Period38CoordinatorInfo {
    pub fn new() -> Dbv0Period0Period38CoordinatorInfo {
        Dbv0Period0Period38CoordinatorInfo {
            name: None,
            direct: None,
        }
    }
}


