/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038QosLimitsMaxJobs : Limits on jobs settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038QosLimitsMaxJobs {
    #[serde(rename = "active_jobs", skip_serializing_if = "Option::is_none")]
    pub active_jobs: Option<Box<crate::models::Dbv0038QosLimitsMaxJobsActiveJobs>>,
}

impl Dbv0038QosLimitsMaxJobs {
    /// Limits on jobs settings
    pub fn new() -> Dbv0038QosLimitsMaxJobs {
        Dbv0038QosLimitsMaxJobs {
            active_jobs: None,
        }
    }
}


