/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038QosLimitsMaxTresMinutesPer : Max TRES minutes per settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038QosLimitsMaxTresMinutesPer {
    /// TRES list of attributes
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<Vec<crate::models::Dbv0038TresListInner>>,
    /// TRES list of attributes
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<Vec<crate::models::Dbv0038TresListInner>>,
    /// TRES list of attributes
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Vec<crate::models::Dbv0038TresListInner>>,
    /// TRES list of attributes
    #[serde(rename = "qos", skip_serializing_if = "Option::is_none")]
    pub qos: Option<Vec<crate::models::Dbv0038TresListInner>>,
}

impl Dbv0038QosLimitsMaxTresMinutesPer {
    /// Max TRES minutes per settings
    pub fn new() -> Dbv0038QosLimitsMaxTresMinutesPer {
        Dbv0038QosLimitsMaxTresMinutesPer {
            job: None,
            account: None,
            user: None,
            qos: None,
        }
    }
}


