/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period37WckeyInfo {
    /// Slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::Dbv0Period0Period37Error>>,
    /// List of wckeys
    #[serde(rename = "wckeys", skip_serializing_if = "Option::is_none")]
    pub wckeys: Option<Vec<crate::models::Dbv0Period0Period37Wckey>>,
}

impl Dbv0Period0Period37WckeyInfo {
    pub fn new() -> Dbv0Period0Period37WckeyInfo {
        Dbv0Period0Period37WckeyInfo {
            errors: None,
            wckeys: None,
        }
    }
}


