/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037AssociationMaxPer : Max per settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037AssociationMaxPer {
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<Box<crate::models::Dbv0037AssociationMaxPerAccount>>,
}

impl Dbv0037AssociationMaxPer {
    /// Max per settings
    pub fn new() -> Dbv0037AssociationMaxPer {
        Dbv0037AssociationMaxPer {
            account: None,
        }
    }
}


