/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037DiagStatistics : dictionary of Slurmdb statistics



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037DiagStatistics {
    /// Unix timestamp of start time
    #[serde(rename = "time_start", skip_serializing_if = "Option::is_none")]
    pub time_start: Option<i32>,
    #[serde(rename = "rollups", skip_serializing_if = "Option::is_none")]
    pub rollups: Option<Vec<crate::models::Dbv0037DiagStatisticsRollupsInner>>,
    #[serde(rename = "RPCs", skip_serializing_if = "Option::is_none")]
    pub rpcs: Option<Vec<crate::models::Dbv0037DiagStatisticsRpcsInner>>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::Dbv0037DiagStatisticsUsersInner>>,
}

impl Dbv0037DiagStatistics {
    /// dictionary of Slurmdb statistics
    pub fn new() -> Dbv0037DiagStatistics {
        Dbv0037DiagStatistics {
            time_start: None,
            rollups: None,
            rpcs: None,
            users: None,
        }
    }
}


