/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period37JobStep {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::Dbv0037JobStepTime>>,
    #[serde(rename = "exit_code", skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<Box<crate::models::Dbv0Period0Period37JobExitCode>>,
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<Box<crate::models::Dbv0037JobStepNodes>>,
    #[serde(rename = "tasks", skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Box<crate::models::Dbv0037JobStepTasks>>,
    /// First process PID
    #[serde(rename = "pid", skip_serializing_if = "Option::is_none")]
    pub pid: Option<String>,
    #[serde(rename = "CPU", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<Box<crate::models::Dbv0037JobStepCpu>>,
    /// User who requested job killed
    #[serde(rename = "kill_request_user", skip_serializing_if = "Option::is_none")]
    pub kill_request_user: Option<String>,
    /// State of job step
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "statistics", skip_serializing_if = "Option::is_none")]
    pub statistics: Option<Box<crate::models::Dbv0037JobStepStatistics>>,
    #[serde(rename = "step", skip_serializing_if = "Option::is_none")]
    pub step: Option<Box<crate::models::Dbv0037JobStepStep>>,
    #[serde(rename = "task", skip_serializing_if = "Option::is_none")]
    pub task: Option<Box<crate::models::Dbv0037JobStepTask>>,
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Box<crate::models::Dbv0037JobStepTres>>,
}

impl Dbv0Period0Period37JobStep {
    pub fn new() -> Dbv0Period0Period37JobStep {
        Dbv0Period0Period37JobStep {
            time: None,
            exit_code: None,
            nodes: None,
            tasks: None,
            pid: None,
            cpu: None,
            kill_request_user: None,
            state: None,
            statistics: None,
            step: None,
            task: None,
            tres: None,
        }
    }
}


