/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037QosLimitsMaxJobsActiveJobsPer : Limits on active jobs per settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037QosLimitsMaxJobsActiveJobsPer {
    /// Max jobs per account
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<i32>,
    /// Max jobs per user
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<i32>,
}

impl Dbv0037QosLimitsMaxJobsActiveJobsPer {
    /// Limits on active jobs per settings
    pub fn new() -> Dbv0037QosLimitsMaxJobsActiveJobsPer {
        Dbv0037QosLimitsMaxJobsActiveJobsPer {
            account: None,
            user: None,
        }
    }
}


