/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobWckey : Job assigned wckey details



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobWckey {
    /// Job assigned wckey
    #[serde(rename = "wckey", skip_serializing_if = "Option::is_none")]
    pub wckey: Option<String>,
    /// wckey flags
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<String>>,
}

impl Dbv0037JobWckey {
    /// Job assigned wckey details
    pub fn new() -> Dbv0037JobWckey {
        Dbv0037JobWckey {
            wckey: None,
            flags: None,
        }
    }
}


