/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0Period0Period38Account : Account description



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period38Account {
    /// List of assigned associations
    #[serde(rename = "associations", skip_serializing_if = "Option::is_none")]
    pub associations: Option<Vec<crate::models::Dbv0Period0Period38AssociationShortInfo>>,
    /// List of assigned coordinators
    #[serde(rename = "coordinators", skip_serializing_if = "Option::is_none")]
    pub coordinators: Option<Vec<crate::models::Dbv0Period0Period38CoordinatorInfo>>,
    /// Description of account
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name of account
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Assigned organization of account
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    /// List of properties of account
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<String>>,
}

impl Dbv0Period0Period38Account {
    /// Account description
    pub fn new() -> Dbv0Period0Period38Account {
        Dbv0Period0Period38Account {
            associations: None,
            coordinators: None,
            description: None,
            name: None,
            organization: None,
            flags: None,
        }
    }
}


