/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobComment : Job comments by type



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobComment {
    /// Administrator set comment
    #[serde(rename = "administrator", skip_serializing_if = "Option::is_none")]
    pub administrator: Option<String>,
    /// Job comment
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<String>,
    /// System set comment
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,
}

impl Dbv0037JobComment {
    /// Job comments by type
    pub fn new() -> Dbv0037JobComment {
        Dbv0037JobComment {
            administrator: None,
            job: None,
            system: None,
        }
    }
}


