/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037DiagStatisticsRpcsInner : Statistics by RPC type



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037DiagStatisticsRpcsInner {
    /// RPC type
    #[serde(rename = "rpc", skip_serializing_if = "Option::is_none")]
    pub rpc: Option<String>,
    /// Number of RPCs
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::Dbv0037DiagStatisticsRpcsInnerTime>>,
}

impl Dbv0037DiagStatisticsRpcsInner {
    /// Statistics by RPC type
    pub fn new() -> Dbv0037DiagStatisticsRpcsInner {
        Dbv0037DiagStatisticsRpcsInner {
            rpc: None,
            count: None,
            time: None,
        }
    }
}


