/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobStepStatisticsEnergy : Statistics of energy



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobStepStatisticsEnergy {
    /// Energy consumed during step
    #[serde(rename = "consumed", skip_serializing_if = "Option::is_none")]
    pub consumed: Option<i32>,
}

impl Dbv0038JobStepStatisticsEnergy {
    /// Statistics of energy
    pub fn new() -> Dbv0038JobStepStatisticsEnergy {
        Dbv0038JobStepStatisticsEnergy {
            consumed: None,
        }
    }
}


