/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobArrayLimits : Limits on array settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobArrayLimits {
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<Box<crate::models::Dbv0037JobArrayLimitsMax>>,
}

impl Dbv0037JobArrayLimits {
    /// Limits on array settings
    pub fn new() -> Dbv0037JobArrayLimits {
        Dbv0037JobArrayLimits {
            max: None,
        }
    }
}


