/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobArrayLimitsMaxRunning : Limits on array settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobArrayLimitsMaxRunning {
    /// Max running tasks in array at any one time
    #[serde(rename = "tasks", skip_serializing_if = "Option::is_none")]
    pub tasks: Option<i32>,
}

impl Dbv0037JobArrayLimitsMaxRunning {
    /// Limits on array settings
    pub fn new() -> Dbv0037JobArrayLimitsMaxRunning {
        Dbv0037JobArrayLimitsMaxRunning {
            tasks: None,
        }
    }
}


