/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038QosLimitsMaxTresMinutes : Max TRES minutes settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038QosLimitsMaxTresMinutes {
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0038QosLimitsMaxTresMinutesPer>>,
}

impl Dbv0038QosLimitsMaxTresMinutes {
    /// Max TRES minutes settings
    pub fn new() -> Dbv0038QosLimitsMaxTresMinutes {
        Dbv0038QosLimitsMaxTresMinutes {
            per: None,
        }
    }
}


