/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobStepTask : Task properties



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobStepTask {
    /// Task distribution type
    #[serde(rename = "distribution", skip_serializing_if = "Option::is_none")]
    pub distribution: Option<String>,
}

impl Dbv0037JobStepTask {
    /// Task properties
    pub fn new() -> Dbv0037JobStepTask {
        Dbv0037JobStepTask {
            distribution: None,
        }
    }
}


