/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobStepNodes : Node details



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobStepNodes {
    /// Total number of nodes in step
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Nodes in step
    #[serde(rename = "range", skip_serializing_if = "Option::is_none")]
    pub range: Option<String>,
}

impl Dbv0037JobStepNodes {
    /// Node details
    pub fn new() -> Dbv0037JobStepNodes {
        Dbv0037JobStepNodes {
            count: None,
            range: None,
        }
    }
}


