/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period39TresUpdate {
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Vec<crate::models::V0Period0Period39Tres>>,
}

impl Dbv0Period0Period39TresUpdate {
    pub fn new() -> Dbv0Period0Period39TresUpdate {
        Dbv0Period0Period39TresUpdate {
            tres: None,
        }
    }
}


