/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038QosLimitsMaxAccruingPer : Max accuring priority per setting



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038QosLimitsMaxAccruingPer {
    /// Max accuring priority per account
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<i32>,
    /// Max accuring priority per user
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<i32>,
}

impl Dbv0038QosLimitsMaxAccruingPer {
    /// Max accuring priority per setting
    pub fn new() -> Dbv0038QosLimitsMaxAccruingPer {
        Dbv0038QosLimitsMaxAccruingPer {
            account: None,
            user: None,
        }
    }
}


