/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobTimeUser : User land time values



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobTimeUser {
    /// Total number of CPU-seconds used by the job in user land, in seconds
    #[serde(rename = "seconds", skip_serializing_if = "Option::is_none")]
    pub seconds: Option<i32>,
    /// Total number of CPU-seconds used by the job in user land, in microseconds
    #[serde(rename = "microseconds", skip_serializing_if = "Option::is_none")]
    pub microseconds: Option<i32>,
}

impl Dbv0037JobTimeUser {
    /// User land time values
    pub fn new() -> Dbv0037JobTimeUser {
        Dbv0037JobTimeUser {
            seconds: None,
            microseconds: None,
        }
    }
}


