/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037AssociationMax : Max settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037AssociationMax {
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Box<crate::models::Dbv0037AssociationMaxJobs>>,
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0037AssociationMaxPer>>,
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Box<crate::models::Dbv0037AssociationMaxTres>>,
}

impl Dbv0037AssociationMax {
    /// Max settings
    pub fn new() -> Dbv0037AssociationMax {
        Dbv0037AssociationMax {
            jobs: None,
            per: None,
            tres: None,
        }
    }
}


