/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038AssociationMax : Max settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038AssociationMax {
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Box<crate::models::Dbv0038AssociationMaxJobs>>,
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0038AssociationMaxPer>>,
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Box<crate::models::Dbv0038AssociationMaxTres>>,
}

impl Dbv0038AssociationMax {
    /// Max settings
    pub fn new() -> Dbv0038AssociationMax {
        Dbv0038AssociationMax {
            jobs: None,
            per: None,
            tres: None,
        }
    }
}


