/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037AssociationMaxTresGroup : Max TRES per group



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037AssociationMaxTresGroup {
    /// TRES list of attributes
    #[serde(rename = "minutes", skip_serializing_if = "Option::is_none")]
    pub minutes: Option<Vec<crate::models::Dbv0037TresListInner>>,
    /// TRES list of attributes
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<Vec<crate::models::Dbv0037TresListInner>>,
}

impl Dbv0037AssociationMaxTresGroup {
    /// Max TRES per group
    pub fn new() -> Dbv0037AssociationMaxTresGroup {
        Dbv0037AssociationMaxTresGroup {
            minutes: None,
            active: None,
        }
    }
}


