/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038AssociationMaxTres : Max TRES settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038AssociationMaxTres {
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0038AssociationMaxTresPer>>,
    /// TRES list of attributes
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<Vec<crate::models::Dbv0038TresListInner>>,
    #[serde(rename = "minutes", skip_serializing_if = "Option::is_none")]
    pub minutes: Option<Box<crate::models::Dbv0038AssociationMaxTresMinutes>>,
}

impl Dbv0038AssociationMaxTres {
    /// Max TRES settings
    pub fn new() -> Dbv0038AssociationMaxTres {
        Dbv0038AssociationMaxTres {
            per: None,
            total: None,
            minutes: None,
        }
    }
}


