/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobTimeTotal : System time values



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobTimeTotal {
    /// Total number of CPU-seconds used by the job, in seconds
    #[serde(rename = "seconds", skip_serializing_if = "Option::is_none")]
    pub seconds: Option<i32>,
    /// Total number of CPU-seconds used by the job, in microseconds
    #[serde(rename = "microseconds", skip_serializing_if = "Option::is_none")]
    pub microseconds: Option<i32>,
}

impl Dbv0038JobTimeTotal {
    /// System time values
    pub fn new() -> Dbv0038JobTimeTotal {
        Dbv0038JobTimeTotal {
            seconds: None,
            microseconds: None,
        }
    }
}


