/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobHet : Heterogeneous Job details (optional)



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobHet {
    /// Parent HetJob id
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<i32>,
    /// Offset of this job to parent
    #[serde(rename = "job_offset", skip_serializing_if = "Option::is_none")]
    pub job_offset: Option<i32>,
}

impl Dbv0038JobHet {
    /// Heterogeneous Job details (optional)
    pub fn new() -> Dbv0038JobHet {
        Dbv0038JobHet {
            job_id: None,
            job_offset: None,
        }
    }
}


