/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038ClusterInfoAssociations : Information about associations



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038ClusterInfoAssociations {
    #[serde(rename = "root", skip_serializing_if = "Option::is_none")]
    pub root: Option<Box<crate::models::Dbv0Period0Period38AssociationShortInfo>>,
}

impl Dbv0038ClusterInfoAssociations {
    /// Information about associations
    pub fn new() -> Dbv0038ClusterInfoAssociations {
        Dbv0038ClusterInfoAssociations {
            root: None,
        }
    }
}


