/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period37TresInfo {
    /// Slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::Dbv0Period0Period37Error>>,
    /// Array of tres
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Vec<Vec<crate::models::Dbv0037TresListInner>>>,
}

impl Dbv0Period0Period37TresInfo {
    pub fn new() -> Dbv0Period0Period37TresInfo {
        Dbv0Period0Period37TresInfo {
            errors: None,
            tres: None,
        }
    }
}


