/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037QosLimitsMaxWallClock : Limit on wallclock settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037QosLimitsMaxWallClock {
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::Dbv0037QosLimitsMaxWallClockPer>>,
}

impl Dbv0037QosLimitsMaxWallClock {
    /// Limit on wallclock settings
    pub fn new() -> Dbv0037QosLimitsMaxWallClock {
        Dbv0037QosLimitsMaxWallClock {
            per: None,
        }
    }
}


