/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period37Error {
    /// Error number
    #[serde(rename = "errno", skip_serializing_if = "Option::is_none")]
    pub errno: Option<i32>,
    /// Error message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl Dbv0Period0Period37Error {
    pub fn new() -> Dbv0Period0Period37Error {
        Dbv0Period0Period37Error {
            errno: None,
            error: None,
        }
    }
}


