/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period39UpdateUsers {
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::V0Period0Period39User>>,
}

impl Dbv0Period0Period39UpdateUsers {
    pub fn new() -> Dbv0Period0Period39UpdateUsers {
        Dbv0Period0Period39UpdateUsers {
            users: None,
        }
    }
}


