/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period38UpdateAccount {
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<crate::models::Dbv0Period0Period38Account>>,
}

impl Dbv0Period0Period38UpdateAccount {
    pub fn new() -> Dbv0Period0Period38UpdateAccount {
        Dbv0Period0Period38UpdateAccount {
            accounts: None,
        }
    }
}


