/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037JobStepTasks : Task properties



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037JobStepTasks {
    /// Number of tasks in step
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl Dbv0037JobStepTasks {
    /// Task properties
    pub fn new() -> Dbv0037JobStepTasks {
        Dbv0037JobStepTasks {
            count: None,
        }
    }
}


