/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0Period0Period37JobExitCode {
    /// Job exit status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Return code from parent process
    #[serde(rename = "return_code", skip_serializing_if = "Option::is_none")]
    pub return_code: Option<i32>,
    #[serde(rename = "signal", skip_serializing_if = "Option::is_none")]
    pub signal: Option<Box<crate::models::Dbv0037JobExitCodeSignal>>,
}

impl Dbv0Period0Period37JobExitCode {
    pub fn new() -> Dbv0Period0Period37JobExitCode {
        Dbv0Period0Period37JobExitCode {
            status: None,
            return_code: None,
            signal: None,
        }
    }
}


