/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038UserDefault : Default settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038UserDefault {
    /// Default account name
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
    /// Default wckey
    #[serde(rename = "wckey", skip_serializing_if = "Option::is_none")]
    pub wckey: Option<String>,
}

impl Dbv0038UserDefault {
    /// Default settings
    pub fn new() -> Dbv0038UserDefault {
        Dbv0038UserDefault {
            account: None,
            wckey: None,
        }
    }
}


