/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037QosLimitsMaxJobs : Limits on jobs settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037QosLimitsMaxJobs {
    #[serde(rename = "active_jobs", skip_serializing_if = "Option::is_none")]
    pub active_jobs: Option<Box<crate::models::Dbv0037QosLimitsMaxJobsActiveJobs>>,
}

impl Dbv0037QosLimitsMaxJobs {
    /// Limits on jobs settings
    pub fn new() -> Dbv0037QosLimitsMaxJobs {
        Dbv0037QosLimitsMaxJobs {
            active_jobs: None,
        }
    }
}


