/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0038JobArrayLimits : Limits on array settings



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0038JobArrayLimits {
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<Box<crate::models::Dbv0038JobArrayLimitsMax>>,
}

impl Dbv0038JobArrayLimits {
    /// Limits on array settings
    pub fn new() -> Dbv0038JobArrayLimits {
        Dbv0038JobArrayLimits {
            max: None,
        }
    }
}


