/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// Dbv0037ClusterInfoController : Information about controller



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dbv0037ClusterInfoController {
    /// Hostname
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// Port number
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
}

impl Dbv0037ClusterInfoController {
    /// Information about controller
    pub fn new() -> Dbv0037ClusterInfoController {
        Dbv0037ClusterInfoController {
            host: None,
            port: None,
        }
    }
}


