/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039PartitionInfoTres {
    #[serde(rename = "configured", skip_serializing_if = "Option::is_none")]
    pub configured: Option<String>,
}

impl V0039PartitionInfoTres {
    pub fn new() -> V0039PartitionInfoTres {
        V0039PartitionInfoTres {
            configured: None,
        }
    }
}


