/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039StepStatistics {
    #[serde(rename = "energy", skip_serializing_if = "Option::is_none")]
    pub energy: Option<Box<crate::models::V0039StepStatisticsEnergy>>,
}

impl V0039StepStatistics {
    pub fn new() -> V0039StepStatistics {
        V0039StepStatistics {
            energy: None,
        }
    }
}


