/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039QosLimitsMinTresPer {
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<Vec<crate::models::V0Period0Period39Tres>>,
}

impl V0039QosLimitsMinTresPer {
    pub fn new() -> V0039QosLimitsMinTresPer {
        V0039QosLimitsMinTresPer {
            job: None,
        }
    }
}


