/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0038NodeAllocationSockets : assignment status of each socket by numeric socket id



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0038NodeAllocationSockets {
    /// assignment status of each core by core id in each socket
    #[serde(rename = "cores", skip_serializing_if = "Option::is_none")]
    pub cores: Option<serde_json::Value>,
}

impl V0038NodeAllocationSockets {
    /// assignment status of each socket by numeric socket id
    pub fn new() -> V0038NodeAllocationSockets {
        V0038NodeAllocationSockets {
            cores: None,
        }
    }
}


