/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039AssocMaxJobs {
    #[serde(rename = "per", skip_serializing_if = "Option::is_none")]
    pub per: Option<Box<crate::models::V0039AssocMaxJobsPer>>,
}

impl V0039AssocMaxJobs {
    pub fn new() -> V0039AssocMaxJobs {
        V0039AssocMaxJobs {
            per: None,
        }
    }
}


