/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0039StatsMsgRpcsByTypeInner : RPC



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039StatsMsgRpcsByTypeInner {
    /// Message type as string
    #[serde(rename = "message_type", skip_serializing_if = "Option::is_none")]
    pub message_type: Option<String>,
    /// Message type as integer
    #[serde(rename = "type_id", skip_serializing_if = "Option::is_none")]
    pub type_id: Option<i32>,
    /// Number of RPCs received
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Average time spent processing RPC in seconds
    #[serde(rename = "average_time", skip_serializing_if = "Option::is_none")]
    pub average_time: Option<i64>,
    /// Total time spent processing RPC in seconds
    #[serde(rename = "total_time", skip_serializing_if = "Option::is_none")]
    pub total_time: Option<i64>,
}

impl V0039StatsMsgRpcsByTypeInner {
    /// RPC
    pub fn new() -> V0039StatsMsgRpcsByTypeInner {
        V0039StatsMsgRpcsByTypeInner {
            message_type: None,
            type_id: None,
            count: None,
            average_time: None,
            total_time: None,
        }
    }
}


