/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0037ReservationPurgeCompleted : If PURGE_COMP flag is set the amount of seconds this reservation will sit idle until it is revoked



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0037ReservationPurgeCompleted {
    /// amount of seconds this reservation will sit idle until it is revoked
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i32>,
}

impl V0037ReservationPurgeCompleted {
    /// If PURGE_COMP flag is set the amount of seconds this reservation will sit idle until it is revoked
    pub fn new() -> V0037ReservationPurgeCompleted {
        V0037ReservationPurgeCompleted {
            time: None,
        }
    }
}


