/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039QosLimitsMin {
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Box<crate::models::V0039QosLimitsMinTres>>,
}

impl V0039QosLimitsMin {
    pub fn new() -> V0039QosLimitsMin {
        V0039QosLimitsMin {
            tres: None,
        }
    }
}


