/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039StepNodes {
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<String>>,
}

impl V0039StepNodes {
    pub fn new() -> V0039StepNodes {
        V0039StepNodes {
            list: None,
        }
    }
}


