/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039QosPreempt {
    #[serde(rename = "exempt_time", skip_serializing_if = "Option::is_none")]
    pub exempt_time: Option<Box<crate::models::V0Period0Period39Uint32NoVal>>,
}

impl V0039QosPreempt {
    pub fn new() -> V0039QosPreempt {
        V0039QosPreempt {
            exempt_time: None,
        }
    }
}


