/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039QosLimits {
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<Box<crate::models::V0039QosLimitsMin>>,
}

impl V0039QosLimits {
    pub fn new() -> V0039QosLimits {
        V0039QosLimits {
            min: None,
        }
    }
}


