/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039AssocMin {
    #[serde(rename = "priority_threshold", skip_serializing_if = "Option::is_none")]
    pub priority_threshold: Option<Box<crate::models::V0Period0Period39Uint32NoVal>>,
}

impl V0039AssocMin {
    pub fn new() -> V0039AssocMin {
        V0039AssocMin {
            priority_threshold: None,
        }
    }
}


