/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039AssocMaxJobsPer {
    #[serde(rename = "wall_clock", skip_serializing_if = "Option::is_none")]
    pub wall_clock: Option<Box<crate::models::V0Period0Period39Uint32NoVal>>,
}

impl V0039AssocMaxJobsPer {
    pub fn new() -> V0039AssocMaxJobsPer {
        V0039AssocMaxJobsPer {
            wall_clock: None,
        }
    }
}


