/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0039MetaSlurm : Slurm information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039MetaSlurm {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<crate::models::V0039MetaSlurmVersion>>,
    /// version specifier
    #[serde(rename = "release", skip_serializing_if = "Option::is_none")]
    pub release: Option<String>,
}

impl V0039MetaSlurm {
    /// Slurm information
    pub fn new() -> V0039MetaSlurm {
        V0039MetaSlurm {
            version: None,
            release: None,
        }
    }
}


