/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039PartitionInfoMinimums {
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<i32>,
}

impl V0039PartitionInfoMinimums {
    pub fn new() -> V0039PartitionInfoMinimums {
        V0039PartitionInfoMinimums {
            nodes: None,
        }
    }
}


