/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039StepCpu {
    #[serde(rename = "governor", skip_serializing_if = "Option::is_none")]
    pub governor: Option<String>,
}

impl V0039StepCpu {
    pub fn new() -> V0039StepCpu {
        V0039StepCpu {
            governor: None,
        }
    }
}


