/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039StepTask {
    #[serde(rename = "distribution", skip_serializing_if = "Option::is_none")]
    pub distribution: Option<String>,
}

impl V0039StepTask {
    pub fn new() -> V0039StepTask {
        V0039StepTask {
            distribution: None,
        }
    }
}


