/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039ClusterRecAssociations {
    #[serde(rename = "root", skip_serializing_if = "Option::is_none")]
    pub root: Option<Box<crate::models::V0Period0Period39AssocShort>>,
}

impl V0039ClusterRecAssociations {
    pub fn new() -> V0039ClusterRecAssociations {
        V0039ClusterRecAssociations {
            root: None,
        }
    }
}


