/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039PartitionInfoMaximums {
    #[serde(rename = "over_time_limit", skip_serializing_if = "Option::is_none")]
    pub over_time_limit: Option<Box<crate::models::V0Period0Period39Uint16NoVal>>,
}

impl V0039PartitionInfoMaximums {
    pub fn new() -> V0039PartitionInfoMaximums {
        V0039PartitionInfoMaximums {
            over_time_limit: None,
        }
    }
}


