/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039PartitionInfoAccounts {
    #[serde(rename = "deny", skip_serializing_if = "Option::is_none")]
    pub deny: Option<String>,
}

impl V0039PartitionInfoAccounts {
    pub fn new() -> V0039PartitionInfoAccounts {
        V0039PartitionInfoAccounts {
            deny: None,
        }
    }
}


