/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0039JobExitCodeSignal : Job exited due to signal



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0039JobExitCodeSignal {
    /// signal numeric ID
    #[serde(rename = "signal_id", skip_serializing_if = "Option::is_none")]
    pub signal_id: Option<i32>,
    /// signal name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl V0039JobExitCodeSignal {
    /// Job exited due to signal
    pub fn new() -> V0039JobExitCodeSignal {
        V0039JobExitCodeSignal {
            signal_id: None,
            name: None,
        }
    }
}


