/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39StatsRec {
    #[serde(rename = "time_start", skip_serializing_if = "Option::is_none")]
    pub time_start: Option<i64>,
    /// list of recorded rollup statistics
    #[serde(rename = "rollups", skip_serializing_if = "Option::is_none")]
    pub rollups: Option<Vec<crate::models::V0039RollupStatsInner>>,
    #[serde(rename = "RPCs", skip_serializing_if = "Option::is_none")]
    pub rpcs: Option<Vec<crate::models::V0Period0Period39StatsRpc>>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<crate::models::V0Period0Period39StatsUser>>,
}

impl V0Period0Period39StatsRec {
    pub fn new() -> V0Period0Period39StatsRec {
        V0Period0Period39StatsRec {
            time_start: None,
            rollups: None,
            rpcs: None,
            users: None,
        }
    }
}


