/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0Period0Period38Signal : POSIX signal name

/// POSIX signal name
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum V0Period0Period38Signal {
    #[serde(rename = "HUP")]
    Hup,
    #[serde(rename = "INT")]
    Int,
    #[serde(rename = "QUIT")]
    Quit,
    #[serde(rename = "ABRT")]
    Abrt,
    #[serde(rename = "KILL")]
    Kill,
    #[serde(rename = "ALRM")]
    Alrm,
    #[serde(rename = "TERM")]
    Term,
    #[serde(rename = "USR1")]
    Usr1,
    #[serde(rename = "USR2")]
    Usr2,
    #[serde(rename = "URG")]
    Urg,
    #[serde(rename = "CONT")]
    Cont,
    #[serde(rename = "STOP")]
    Stop,
    #[serde(rename = "TSTP")]
    Tstp,
    #[serde(rename = "TTIN")]
    Ttin,
    #[serde(rename = "TTOU")]
    Ttou,

}

impl ToString for V0Period0Period38Signal {
    fn to_string(&self) -> String {
        match self {
            Self::Hup => String::from("HUP"),
            Self::Int => String::from("INT"),
            Self::Quit => String::from("QUIT"),
            Self::Abrt => String::from("ABRT"),
            Self::Kill => String::from("KILL"),
            Self::Alrm => String::from("ALRM"),
            Self::Term => String::from("TERM"),
            Self::Usr1 => String::from("USR1"),
            Self::Usr2 => String::from("USR2"),
            Self::Urg => String::from("URG"),
            Self::Cont => String::from("CONT"),
            Self::Stop => String::from("STOP"),
            Self::Tstp => String::from("TSTP"),
            Self::Ttin => String::from("TTIN"),
            Self::Ttou => String::from("TTOU"),
        }
    }
}

impl Default for V0Period0Period38Signal {
    fn default() -> V0Period0Period38Signal {
        Self::Hup
    }
}




