/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39PowerMgmtData {
    #[serde(rename = "maximum_watts", skip_serializing_if = "Option::is_none")]
    pub maximum_watts: Option<Box<crate::models::V0Period0Period39Uint32NoVal>>,
    #[serde(rename = "current_watts", skip_serializing_if = "Option::is_none")]
    pub current_watts: Option<i32>,
    #[serde(rename = "total_energy", skip_serializing_if = "Option::is_none")]
    pub total_energy: Option<i64>,
    #[serde(rename = "new_maximum_watts", skip_serializing_if = "Option::is_none")]
    pub new_maximum_watts: Option<i32>,
    #[serde(rename = "peak_watts", skip_serializing_if = "Option::is_none")]
    pub peak_watts: Option<i32>,
    #[serde(rename = "lowest_watts", skip_serializing_if = "Option::is_none")]
    pub lowest_watts: Option<i32>,
    #[serde(rename = "new_job_time", skip_serializing_if = "Option::is_none")]
    pub new_job_time: Option<i64>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<i32>,
    #[serde(rename = "time_start_day", skip_serializing_if = "Option::is_none")]
    pub time_start_day: Option<i64>,
}

impl V0Period0Period39PowerMgmtData {
    pub fn new() -> V0Period0Period39PowerMgmtData {
        V0Period0Period39PowerMgmtData {
            maximum_watts: None,
            current_watts: None,
            total_energy: None,
            new_maximum_watts: None,
            peak_watts: None,
            lowest_watts: None,
            new_job_time: None,
            state: None,
            time_start_day: None,
        }
    }
}


