/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period38DiagRpcu {
    /// user
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// user id
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// rpc count
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// average time
    #[serde(rename = "average_time", skip_serializing_if = "Option::is_none")]
    pub average_time: Option<i32>,
    /// total time
    #[serde(rename = "total_time", skip_serializing_if = "Option::is_none")]
    pub total_time: Option<i32>,
}

impl V0Period0Period38DiagRpcu {
    pub fn new() -> V0Period0Period38DiagRpcu {
        V0Period0Period38DiagRpcu {
            user: None,
            user_id: None,
            count: None,
            average_time: None,
            total_time: None,
        }
    }
}


