/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period38DiagRpcm {
    /// message type
    #[serde(rename = "message_type", skip_serializing_if = "Option::is_none")]
    pub message_type: Option<String>,
    /// message type id
    #[serde(rename = "type_id", skip_serializing_if = "Option::is_none")]
    pub type_id: Option<i32>,
    /// rpc count
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// average time
    #[serde(rename = "average_time", skip_serializing_if = "Option::is_none")]
    pub average_time: Option<i32>,
    /// total time
    #[serde(rename = "total_time", skip_serializing_if = "Option::is_none")]
    pub total_time: Option<i32>,
}

impl V0Period0Period38DiagRpcm {
    pub fn new() -> V0Period0Period38DiagRpcm {
        V0Period0Period38DiagRpcm {
            message_type: None,
            type_id: None,
            count: None,
            average_time: None,
            total_time: None,
        }
    }
}


