/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period37JobResources {
    /// list of assigned job nodes
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<String>,
    /// number of assigned job cpus
    #[serde(rename = "allocated_cpus", skip_serializing_if = "Option::is_none")]
    pub allocated_cpus: Option<i32>,
    /// number of assigned job hosts
    #[serde(rename = "allocated_hosts", skip_serializing_if = "Option::is_none")]
    pub allocated_hosts: Option<i32>,
    /// node allocations
    #[serde(rename = "allocated_nodes", skip_serializing_if = "Option::is_none")]
    pub allocated_nodes: Option<Vec<crate::models::V0Period0Period37NodeAllocation>>,
}

impl V0Period0Period37JobResources {
    pub fn new() -> V0Period0Period37JobResources {
        V0Period0Period37JobResources {
            nodes: None,
            allocated_cpus: None,
            allocated_hosts: None,
            allocated_nodes: None,
        }
    }
}


