/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39AcctGatherEnergy {
    #[serde(rename = "average_watts", skip_serializing_if = "Option::is_none")]
    pub average_watts: Option<i32>,
    #[serde(rename = "base_consumed_energy", skip_serializing_if = "Option::is_none")]
    pub base_consumed_energy: Option<i64>,
    #[serde(rename = "consumed_energy", skip_serializing_if = "Option::is_none")]
    pub consumed_energy: Option<i64>,
    #[serde(rename = "current_watts", skip_serializing_if = "Option::is_none")]
    pub current_watts: Option<i32>,
    #[serde(rename = "previous_consumed_energy", skip_serializing_if = "Option::is_none")]
    pub previous_consumed_energy: Option<i64>,
    #[serde(rename = "last_collected", skip_serializing_if = "Option::is_none")]
    pub last_collected: Option<i64>,
}

impl V0Period0Period39AcctGatherEnergy {
    pub fn new() -> V0Period0Period39AcctGatherEnergy {
        V0Period0Period39AcctGatherEnergy {
            average_watts: None,
            base_consumed_energy: None,
            consumed_energy: None,
            current_watts: None,
            previous_consumed_energy: None,
            last_collected: None,
        }
    }
}


