/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39JobRes {
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<String>,
    #[serde(rename = "allocated_cores", skip_serializing_if = "Option::is_none")]
    pub allocated_cores: Option<i32>,
    #[serde(rename = "allocated_cpus", skip_serializing_if = "Option::is_none")]
    pub allocated_cpus: Option<i32>,
    #[serde(rename = "allocated_hosts", skip_serializing_if = "Option::is_none")]
    pub allocated_hosts: Option<i32>,
    /// job node resources
    #[serde(rename = "allocated_nodes", skip_serializing_if = "Option::is_none")]
    pub allocated_nodes: Option<Vec<serde_json::Value>>,
}

impl V0Period0Period39JobRes {
    pub fn new() -> V0Period0Period39JobRes {
        V0Period0Period39JobRes {
            nodes: None,
            allocated_cores: None,
            allocated_cpus: None,
            allocated_hosts: None,
            allocated_nodes: None,
        }
    }
}


