/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0Period0Period39WckeyTag : wckey details



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39WckeyTag {
    /// wckey
    #[serde(rename = "wckey", skip_serializing_if = "Option::is_none")]
    pub wckey: Option<String>,
    /// active flags
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<Flags>>,
}

impl V0Period0Period39WckeyTag {
    /// wckey details
    pub fn new() -> V0Period0Period39WckeyTag {
        V0Period0Period39WckeyTag {
            wckey: None,
            flags: None,
        }
    }
}

/// active flags
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Flags {
    #[serde(rename = "ASSIGNED_DEFAULT")]
    AssignedDefault,
}

impl Default for Flags {
    fn default() -> Flags {
        Self::AssignedDefault
    }
}

