/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0Period0Period39JobExitCode : job exit details



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39JobExitCode {
    /// exit status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// return code (numeric)
    #[serde(rename = "return_code", skip_serializing_if = "Option::is_none")]
    pub return_code: Option<i32>,
    #[serde(rename = "signal", skip_serializing_if = "Option::is_none")]
    pub signal: Option<Box<crate::models::V0039JobExitCodeSignal>>,
}

impl V0Period0Period39JobExitCode {
    /// job exit details
    pub fn new() -> V0Period0Period39JobExitCode {
        V0Period0Period39JobExitCode {
            status: None,
            return_code: None,
            signal: None,
        }
    }
}


