/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period37JobsResponse {
    /// slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::V0Period0Period37Error>>,
    /// job descriptions
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Vec<crate::models::V0Period0Period37JobResponseProperties>>,
}

impl V0Period0Period37JobsResponse {
    pub fn new() -> V0Period0Period37JobsResponse {
        V0Period0Period37JobsResponse {
            errors: None,
            jobs: None,
        }
    }
}


