/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39ControllerPing {
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "pinged", skip_serializing_if = "Option::is_none")]
    pub pinged: Option<String>,
    #[serde(rename = "latency", skip_serializing_if = "Option::is_none")]
    pub latency: Option<i64>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
}

impl V0Period0Period39ControllerPing {
    pub fn new() -> V0Period0Period39ControllerPing {
        V0Period0Period39ControllerPing {
            hostname: None,
            pinged: None,
            latency: None,
            mode: None,
        }
    }
}


