/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period37ReservationsResponse {
    /// slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::V0Period0Period37Error>>,
    /// reservation info
    #[serde(rename = "reservations", skip_serializing_if = "Option::is_none")]
    pub reservations: Option<Vec<crate::models::V0Period0Period37Reservation>>,
}

impl V0Period0Period37ReservationsResponse {
    pub fn new() -> V0Period0Period37ReservationsResponse {
        V0Period0Period37ReservationsResponse {
            errors: None,
            reservations: None,
        }
    }
}


