/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39Step {
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::V0039StepTime>>,
    #[serde(rename = "exit_code", skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<Box<crate::models::V0Period0Period39JobExitCode>>,
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<Box<crate::models::V0039StepNodes>>,
    #[serde(rename = "tasks", skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Box<crate::models::V0039StepTasks>>,
    #[serde(rename = "pid", skip_serializing_if = "Option::is_none")]
    pub pid: Option<String>,
    #[serde(rename = "CPU", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<Box<crate::models::V0039StepCpu>>,
    #[serde(rename = "kill_request_user", skip_serializing_if = "Option::is_none")]
    pub kill_request_user: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "statistics", skip_serializing_if = "Option::is_none")]
    pub statistics: Option<Box<crate::models::V0039StepStatistics>>,
    #[serde(rename = "step", skip_serializing_if = "Option::is_none")]
    pub step: Option<Box<crate::models::V0039JobReservation>>,
    #[serde(rename = "task", skip_serializing_if = "Option::is_none")]
    pub task: Option<Box<crate::models::V0039StepTask>>,
    #[serde(rename = "tres", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Box<crate::models::V0039StepTres>>,
}

impl V0Period0Period39Step {
    pub fn new() -> V0Period0Period39Step {
        V0Period0Period39Step {
            time: None,
            exit_code: None,
            nodes: None,
            tasks: None,
            pid: None,
            cpu: None,
            kill_request_user: None,
            state: None,
            statistics: None,
            step: None,
            task: None,
            tres: None,
        }
    }
}


