/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period37NodesResponse {
    /// slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::V0Period0Period37Error>>,
    /// nodes info
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<Vec<crate::models::V0Period0Period37Node>>,
}

impl V0Period0Period37NodesResponse {
    pub fn new() -> V0Period0Period37NodesResponse {
        V0Period0Period37NodesResponse {
            errors: None,
            nodes: None,
        }
    }
}


