/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39JobSubmissionResponse {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::V0Period0Period39Meta>>,
    /// Slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::V0Period0Period39Error>>,
    /// Slurm warnings
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<crate::models::V0Period0Period39Warning>>,
    /// new job ID
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<i32>,
    /// new job step ID
    #[serde(rename = "step_id", skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,
    /// Message to user from job_submit plugin
    #[serde(rename = "job_submit_user_msg", skip_serializing_if = "Option::is_none")]
    pub job_submit_user_msg: Option<String>,
}

impl V0Period0Period39JobSubmissionResponse {
    pub fn new() -> V0Period0Period39JobSubmissionResponse {
        V0Period0Period39JobSubmissionResponse {
            meta: None,
            errors: None,
            warnings: None,
            job_id: None,
            step_id: None,
            job_submit_user_msg: None,
        }
    }
}


