/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period38Meta {
    #[serde(rename = "plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<Box<crate::models::V0038MetaPlugin>>,
    #[serde(rename = "Slurm", skip_serializing_if = "Option::is_none")]
    pub slurm: Option<Box<crate::models::V0038MetaSlurm>>,
}

impl V0Period0Period38Meta {
    pub fn new() -> V0Period0Period38Meta {
        V0Period0Period38Meta {
            plugin: None,
            slurm: None,
        }
    }
}


