/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period37JobSubmission {
    /// Executable script (full contents) to run in batch step
    #[serde(rename = "script")]
    pub script: String,
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<Box<crate::models::V0Period0Period37JobProperties>>,
    /// Properties of an HetJob
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Vec<crate::models::V0Period0Period37JobProperties>>,
}

impl V0Period0Period37JobSubmission {
    pub fn new(script: String) -> V0Period0Period37JobSubmission {
        V0Period0Period37JobSubmission {
            script,
            job: None,
            jobs: None,
        }
    }
}


