/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39StatsRpc {
    #[serde(rename = "rpc", skip_serializing_if = "Option::is_none")]
    pub rpc: Option<String>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<Box<crate::models::V0039StatsRpcTime>>,
}

impl V0Period0Period39StatsRpc {
    pub fn new() -> V0Period0Period39StatsRpc {
        V0Period0Period39StatsRpc {
            rpc: None,
            count: None,
            time: None,
        }
    }
}


