/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39Coord {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "direct", skip_serializing_if = "Option::is_none")]
    pub direct: Option<bool>,
}

impl V0Period0Period39Coord {
    pub fn new(name: String) -> V0Period0Period39Coord {
        V0Period0Period39Coord {
            name,
            direct: None,
        }
    }
}


