/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39Error {
    /// Slurm internal error number
    #[serde(rename = "error_number", skip_serializing_if = "Option::is_none")]
    pub error_number: Option<i32>,
    /// Error message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Where error occurred in the source
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Explaination of cause of error
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl V0Period0Period39Error {
    pub fn new() -> V0Period0Period39Error {
        V0Period0Period39Error {
            error_number: None,
            error: None,
            source: None,
            description: None,
        }
    }
}


