/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */

/// V0Period0Period39SlurmStepId : step details



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39SlurmStepId {
    /// JobID
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<i32>,
    /// HetStep
    #[serde(rename = "step_het_component", skip_serializing_if = "Option::is_none")]
    pub step_het_component: Option<i32>,
    #[serde(rename = "step_id", skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,
}

impl V0Period0Period39SlurmStepId {
    /// step details
    pub fn new() -> V0Period0Period39SlurmStepId {
        V0Period0Period39SlurmStepId {
            job_id: None,
            step_het_component: None,
            step_id: None,
        }
    }
}


