/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39ReservationCoreSpec {
    #[serde(rename = "node", skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    #[serde(rename = "core", skip_serializing_if = "Option::is_none")]
    pub core: Option<String>,
}

impl V0Period0Period39ReservationCoreSpec {
    pub fn new() -> V0Period0Period39ReservationCoreSpec {
        V0Period0Period39ReservationCoreSpec {
            node: None,
            core: None,
        }
    }
}


