/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39Accounting {
    #[serde(rename = "allocated", skip_serializing_if = "Option::is_none")]
    pub allocated: Option<Box<crate::models::V0039AccountingAllocated>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    #[serde(rename = "TRES", skip_serializing_if = "Option::is_none")]
    pub tres: Option<Box<crate::models::V0Period0Period39Tres>>,
}

impl V0Period0Period39Accounting {
    pub fn new() -> V0Period0Period39Accounting {
        V0Period0Period39Accounting {
            allocated: None,
            id: None,
            start: None,
            tres: None,
        }
    }
}


