/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period37Pings {
    /// slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::V0Period0Period37Error>>,
    /// slurm controller pings
    #[serde(rename = "pings", skip_serializing_if = "Option::is_none")]
    pub pings: Option<Vec<crate::models::V0Period0Period37Ping>>,
}

impl V0Period0Period37Pings {
    pub fn new() -> V0Period0Period37Pings {
        V0Period0Period37Pings {
            errors: None,
            pings: None,
        }
    }
}


