/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period37PartitionsResponse {
    /// slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::V0Period0Period37Error>>,
    /// partition info
    #[serde(rename = "partitions", skip_serializing_if = "Option::is_none")]
    pub partitions: Option<Vec<crate::models::V0Period0Period37Partition>>,
}

impl V0Period0Period37PartitionsResponse {
    pub fn new() -> V0Period0Period37PartitionsResponse {
        V0Period0Period37PartitionsResponse {
            errors: None,
            partitions: None,
        }
    }
}


