/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39User {
    #[serde(rename = "administrator_level", skip_serializing_if = "Option::is_none")]
    pub administrator_level: Option<Vec<AdministratorLevel>>,
    #[serde(rename = "associations", skip_serializing_if = "Option::is_none")]
    pub associations: Option<Vec<crate::models::V0Period0Period39AssocShort>>,
    #[serde(rename = "coordinators", skip_serializing_if = "Option::is_none")]
    pub coordinators: Option<Vec<crate::models::V0Period0Period39Coord>>,
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<Box<crate::models::V0039UserDefault>>,
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<Flags>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "old_name", skip_serializing_if = "Option::is_none")]
    pub old_name: Option<String>,
    #[serde(rename = "wckeys", skip_serializing_if = "Option::is_none")]
    pub wckeys: Option<Vec<crate::models::V0Period0Period39Wckey>>,
}

impl V0Period0Period39User {
    pub fn new(name: String) -> V0Period0Period39User {
        V0Period0Period39User {
            administrator_level: None,
            associations: None,
            coordinators: None,
            default: None,
            flags: None,
            name,
            old_name: None,
            wckeys: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AdministratorLevel {
    #[serde(rename = "Not Set")]
    NotSet,
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Operator")]
    Operator,
    #[serde(rename = "Administrator")]
    Administrator,
}

impl Default for AdministratorLevel {
    fn default() -> AdministratorLevel {
        Self::NotSet
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Flags {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "DELETED")]
    Deleted,
}

impl Default for Flags {
    fn default() -> Flags {
        Self::None
    }
}

