/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period39License {
    #[serde(rename = "LicenseName", skip_serializing_if = "Option::is_none")]
    pub license_name: Option<String>,
    #[serde(rename = "Total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "Used", skip_serializing_if = "Option::is_none")]
    pub used: Option<i32>,
    #[serde(rename = "Free", skip_serializing_if = "Option::is_none")]
    pub free: Option<i32>,
    #[serde(rename = "Remote", skip_serializing_if = "Option::is_none")]
    pub remote: Option<bool>,
    #[serde(rename = "Reserved", skip_serializing_if = "Option::is_none")]
    pub reserved: Option<i32>,
    #[serde(rename = "LastConsumed", skip_serializing_if = "Option::is_none")]
    pub last_consumed: Option<i32>,
    #[serde(rename = "LastDeficit", skip_serializing_if = "Option::is_none")]
    pub last_deficit: Option<i32>,
    #[serde(rename = "LastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<i64>,
}

impl V0Period0Period39License {
    pub fn new() -> V0Period0Period39License {
        V0Period0Period39License {
            license_name: None,
            total: None,
            used: None,
            free: None,
            remote: None,
            reserved: None,
            last_consumed: None,
            last_deficit: None,
            last_update: None,
        }
    }
}


