/*
 * Slurm Rest API
 *
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V0Period0Period38Licenses {
    /// slurm errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::V0Period0Period38Error>>,
    /// licenses info
    #[serde(rename = "licenses", skip_serializing_if = "Option::is_none")]
    pub licenses: Option<Vec<crate::models::V0Period0Period38License>>,
}

impl V0Period0Period38Licenses {
    pub fn new() -> V0Period0Period38Licenses {
        V0Period0Period38Licenses {
            errors: None,
            licenses: None,
        }
    }
}


